sudo: required
services:
  - docker
before_install:
  - docker build -t sairamsun/myimage -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true sairamsun/myimage npm run test
after_success:
  - docker build -t sairamsun/multi-client ./client
  - docker build -t sairamsun/multi-nginx ./nginx
  - docker build -t sairamsun/multi-server ./server
  - docker build -t sairamsun/multi-worker ./worker
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin 
  - cd ./client | docker push sairamsun/multi-client
  - cd ./nginx | docker push sairamsun/multi-nginx
  - cd ./server | docker push sairamsun/multi-server
  - cd ./worker | docker push sairamsun/multi-worker