sudo: required
services:
  - docker
before_install:
  - docker build -t sairamsun/myimage -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true sairamsun/myimage npm run test
after_success:
  - docker build -t sairamsun/multi-client ./client
  - docker build -t sairamsun/multi-nginx ./nginx
  - docker build -t sairamsun/multi-server ./server
  - docker build -t sairamsun/multi-worker ./worker
  #login into GitHub
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin 
  #push images to DockerHub
  - docker push sairamsun/multi-client
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin 
  - docker push sairamsun/multi-nginx
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin 
  - docker push sairamsun/multi-server
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin 
  - docker push sairamsun/multi-worker